spring.application.name=hospital
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.servlet.context-path=/api/v1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.profiles.active=local
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

#security-config

jwt.secretKey=wa5d14a68w1d14rth1yj464ef4juytkm4j4ry4wr6y35r4g683aw4d3a8w1d35a1d5aw1d4w13da1wd5a